# Generated by Django 3.1.3 on 2020-12-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('userPage', models.URLField(null=True)),
                ('profileImage', models.ImageField(default='', null=True, upload_to='image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
